---
swagger: "2.0"
info:
  description: "standard public schema"
  version: "0.5.0.0 (d8896be)"
  title: "PostgREST API"
host: "0.0.0.0:3000"
basePath: "/"
schemes:
- "http"
consumes:
- "application/json"
- "application/vnd.pgrst.object+json"
- "text/csv"
produces:
- "application/json"
- "application/vnd.pgrst.object+json"
- "text/csv"
paths:
  /:
    get:
      tags:
      - "Introspection"
      summary: "OpenAPI description (this document)"
      produces:
      - "application/openapi+json"
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
  /addrs:
    get:
      tags:
      - "addrs"
      parameters:
      - name: "addr"
        in: "query"
        required: false
        type: "string"
        format: "character varying"
        x-exportParamName: "Addr"
      - name: "balance"
        in: "query"
        required: false
        type: "string"
        format: "numeric"
        x-exportParamName: "Balance"
      - name: "select"
        in: "query"
        description: "Filtering Columns"
        required: false
        type: "string"
        x-exportParamName: "Select_"
      - name: "order"
        in: "query"
        description: "Ordering"
        required: false
        type: "string"
        x-exportParamName: "Order"
      - name: "Range"
        in: "header"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        x-exportParamName: "Range_"
      - name: "Range-Unit"
        in: "header"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        default: "items"
        x-exportParamName: "RangeUnit"
      - name: "offset"
        in: "query"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        x-exportParamName: "Offset"
      - name: "limit"
        in: "query"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        x-exportParamName: "Limit"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "count=none"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/addrs"
        206:
          description: "Partial Content"
    post:
      tags:
      - "addrs"
      parameters:
      - in: "body"
        name: "addrs"
        description: "addrs"
        required: false
        schema:
          $ref: "#/definitions/addrs"
        x-exportParamName: "Addrs"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "return=representation"
        - "return=minimal"
        - "return=none"
        x-exportParamName: "Prefer"
      responses:
        201:
          description: "Created"
    delete:
      tags:
      - "addrs"
      parameters:
      - name: "addr"
        in: "query"
        required: false
        type: "string"
        format: "character varying"
        x-exportParamName: "Addr"
      - name: "balance"
        in: "query"
        required: false
        type: "string"
        format: "numeric"
        x-exportParamName: "Balance"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "return=representation"
        - "return=minimal"
        - "return=none"
        x-exportParamName: "Prefer"
      responses:
        204:
          description: "No Content"
    patch:
      tags:
      - "addrs"
      parameters:
      - name: "addr"
        in: "query"
        required: false
        type: "string"
        format: "character varying"
        x-exportParamName: "Addr"
      - name: "balance"
        in: "query"
        required: false
        type: "string"
        format: "numeric"
        x-exportParamName: "Balance"
      - in: "body"
        name: "addrs"
        description: "addrs"
        required: false
        schema:
          $ref: "#/definitions/addrs"
        x-exportParamName: "Addrs"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "return=representation"
        - "return=minimal"
        - "return=none"
        x-exportParamName: "Prefer"
      responses:
        204:
          description: "No Content"
  /blocks:
    get:
      tags:
      - "blocks"
      parameters:
      - name: "block"
        in: "query"
        required: false
        type: "string"
        format: "integer"
        x-exportParamName: "Block"
      - name: "select"
        in: "query"
        description: "Filtering Columns"
        required: false
        type: "string"
        x-exportParamName: "Select_"
      - name: "order"
        in: "query"
        description: "Ordering"
        required: false
        type: "string"
        x-exportParamName: "Order"
      - name: "Range"
        in: "header"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        x-exportParamName: "Range_"
      - name: "Range-Unit"
        in: "header"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        default: "items"
        x-exportParamName: "RangeUnit"
      - name: "offset"
        in: "query"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        x-exportParamName: "Offset"
      - name: "limit"
        in: "query"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        x-exportParamName: "Limit"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "count=none"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/blocks"
        206:
          description: "Partial Content"
    post:
      tags:
      - "blocks"
      parameters:
      - in: "body"
        name: "blocks"
        description: "blocks"
        required: false
        schema:
          $ref: "#/definitions/blocks"
        x-exportParamName: "Blocks"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "return=representation"
        - "return=minimal"
        - "return=none"
        x-exportParamName: "Prefer"
      responses:
        201:
          description: "Created"
    delete:
      tags:
      - "blocks"
      parameters:
      - name: "block"
        in: "query"
        required: false
        type: "string"
        format: "integer"
        x-exportParamName: "Block"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "return=representation"
        - "return=minimal"
        - "return=none"
        x-exportParamName: "Prefer"
      responses:
        204:
          description: "No Content"
    patch:
      tags:
      - "blocks"
      parameters:
      - name: "block"
        in: "query"
        required: false
        type: "string"
        format: "integer"
        x-exportParamName: "Block"
      - in: "body"
        name: "blocks"
        description: "blocks"
        required: false
        schema:
          $ref: "#/definitions/blocks"
        x-exportParamName: "Blocks"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "return=representation"
        - "return=minimal"
        - "return=none"
        x-exportParamName: "Prefer"
      responses:
        204:
          description: "No Content"
  /contracts:
    get:
      tags:
      - "contracts"
      parameters:
      - name: "addr"
        in: "query"
        required: false
        type: "string"
        format: "character varying"
        x-exportParamName: "Addr"
      - name: "bytecode"
        in: "query"
        required: false
        type: "string"
        format: "text"
        x-exportParamName: "Bytecode"
      - name: "balance"
        in: "query"
        required: false
        type: "string"
        format: "numeric"
        x-exportParamName: "Balance"
      - name: "select"
        in: "query"
        description: "Filtering Columns"
        required: false
        type: "string"
        x-exportParamName: "Select_"
      - name: "order"
        in: "query"
        description: "Ordering"
        required: false
        type: "string"
        x-exportParamName: "Order"
      - name: "Range"
        in: "header"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        x-exportParamName: "Range_"
      - name: "Range-Unit"
        in: "header"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        default: "items"
        x-exportParamName: "RangeUnit"
      - name: "offset"
        in: "query"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        x-exportParamName: "Offset"
      - name: "limit"
        in: "query"
        description: "Limiting and Pagination"
        required: false
        type: "string"
        x-exportParamName: "Limit"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "count=none"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/contracts"
        206:
          description: "Partial Content"
    post:
      tags:
      - "contracts"
      parameters:
      - in: "body"
        name: "contracts"
        description: "contracts"
        required: false
        schema:
          $ref: "#/definitions/contracts"
        x-exportParamName: "Contracts"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "return=representation"
        - "return=minimal"
        - "return=none"
        x-exportParamName: "Prefer"
      responses:
        201:
          description: "Created"
    delete:
      tags:
      - "contracts"
      parameters:
      - name: "addr"
        in: "query"
        required: false
        type: "string"
        format: "character varying"
        x-exportParamName: "Addr"
      - name: "bytecode"
        in: "query"
        required: false
        type: "string"
        format: "text"
        x-exportParamName: "Bytecode"
      - name: "balance"
        in: "query"
        required: false
        type: "string"
        format: "numeric"
        x-exportParamName: "Balance"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "return=representation"
        - "return=minimal"
        - "return=none"
        x-exportParamName: "Prefer"
      responses:
        204:
          description: "No Content"
    patch:
      tags:
      - "contracts"
      parameters:
      - name: "addr"
        in: "query"
        required: false
        type: "string"
        format: "character varying"
        x-exportParamName: "Addr"
      - name: "bytecode"
        in: "query"
        required: false
        type: "string"
        format: "text"
        x-exportParamName: "Bytecode"
      - name: "balance"
        in: "query"
        required: false
        type: "string"
        format: "numeric"
        x-exportParamName: "Balance"
      - in: "body"
        name: "contracts"
        description: "contracts"
        required: false
        schema:
          $ref: "#/definitions/contracts"
        x-exportParamName: "Contracts"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "return=representation"
        - "return=minimal"
        - "return=none"
        x-exportParamName: "Prefer"
      responses:
        204:
          description: "No Content"
definitions:
  addrs:
    type: "object"
    properties:
      addr:
        type: "string"
        format: "character varying"
        description: "Note:\nThis is a Primary Key.<pk/>"
        maxLength: 42
      balance:
        type: "number"
        format: "numeric"
    example:
      balance: 0.80082819046101150206595775671303272247314453125
      addr: "addr"
  blocks:
    type: "object"
    properties:
      block:
        type: "integer"
        format: "integer"
        description: "Note:\nThis is a Primary Key.<pk/>"
    example:
      block: 0
  contracts:
    type: "object"
    properties:
      addr:
        type: "string"
        format: "character varying"
        description: "Note:\nThis is a Primary Key.<pk/>"
        maxLength: 42
      bytecode:
        type: "string"
        format: "text"
      balance:
        type: "number"
        format: "numeric"
    example:
      bytecode: "bytecode"
      balance: 0.80082819046101150206595775671303272247314453125
      addr: "addr"
parameters:
  preferParams:
    name: "Prefer"
    in: "header"
    description: "Preference"
    required: false
    type: "string"
    enum:
    - "params=single-object"
  preferReturn:
    name: "Prefer"
    in: "header"
    description: "Preference"
    required: false
    type: "string"
    enum:
    - "return=representation"
    - "return=minimal"
    - "return=none"
    x-exportParamName: "Prefer"
  preferCount:
    name: "Prefer"
    in: "header"
    description: "Preference"
    required: false
    type: "string"
    enum:
    - "count=none"
    x-exportParamName: "Prefer"
  select:
    name: "select"
    in: "query"
    description: "Filtering Columns"
    required: false
    type: "string"
    x-exportParamName: "Select_"
  order:
    name: "order"
    in: "query"
    description: "Ordering"
    required: false
    type: "string"
    x-exportParamName: "Order"
  range:
    name: "Range"
    in: "header"
    description: "Limiting and Pagination"
    required: false
    type: "string"
    x-exportParamName: "Range_"
  rangeUnit:
    name: "Range-Unit"
    in: "header"
    description: "Limiting and Pagination"
    required: false
    type: "string"
    default: "items"
    x-exportParamName: "RangeUnit"
  offset:
    name: "offset"
    in: "query"
    description: "Limiting and Pagination"
    required: false
    type: "string"
    x-exportParamName: "Offset"
  limit:
    name: "limit"
    in: "query"
    description: "Limiting and Pagination"
    required: false
    type: "string"
    x-exportParamName: "Limit"
  body.addrs:
    in: "body"
    name: "addrs"
    description: "addrs"
    required: false
    schema:
      $ref: "#/definitions/addrs"
    x-exportParamName: "Addrs"
  rowFilter.addrs.addr:
    name: "addr"
    in: "query"
    required: false
    type: "string"
    format: "character varying"
    x-exportParamName: "Addr"
  rowFilter.addrs.balance:
    name: "balance"
    in: "query"
    required: false
    type: "string"
    format: "numeric"
    x-exportParamName: "Balance"
  body.blocks:
    in: "body"
    name: "blocks"
    description: "blocks"
    required: false
    schema:
      $ref: "#/definitions/blocks"
    x-exportParamName: "Blocks"
  rowFilter.blocks.block:
    name: "block"
    in: "query"
    required: false
    type: "string"
    format: "integer"
    x-exportParamName: "Block"
  body.contracts:
    in: "body"
    name: "contracts"
    description: "contracts"
    required: false
    schema:
      $ref: "#/definitions/contracts"
    x-exportParamName: "Contracts"
  rowFilter.contracts.addr:
    name: "addr"
    in: "query"
    required: false
    type: "string"
    format: "character varying"
    x-exportParamName: "Addr"
  rowFilter.contracts.bytecode:
    name: "bytecode"
    in: "query"
    required: false
    type: "string"
    format: "text"
    x-exportParamName: "Bytecode"
  rowFilter.contracts.balance:
    name: "balance"
    in: "query"
    required: false
    type: "string"
    format: "numeric"
    x-exportParamName: "Balance"
externalDocs:
  description: "PostgREST Documentation"
  url: "https://postgrest.org/en/v5.0/api.html"
