---
swagger: "2.0"
info:
  description: "standard public schema"
  version: "0.5.0.0 (d8896be)"
  title: "PostgREST API"
host: "0.0.0.0:3000"
basePath: "/"
schemes:
- "http"
consumes:
- "application/json"
- "application/vnd.pgrst.object+json"
- "text/csv"
produces:
- "application/json"
- "application/vnd.pgrst.object+json"
- "text/csv"
paths:
  /:
    get:
      tags:
      - "Introspection"
      summary: "OpenAPI description (this document)"
      produces:
      - "application/openapi+json"
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
  /rpc/crypt:
    post:
      tags:
      - "(rpc) crypt"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_sym_encrypt:
    post:
      tags:
      - "(rpc) pgp_sym_encrypt"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/encrypt_iv:
    post:
      tags:
      - "(rpc) encrypt_iv"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/encrypt:
    post:
      tags:
      - "(rpc) encrypt"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_pub_encrypt:
    post:
      tags:
      - "(rpc) pgp_pub_encrypt"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/gen_random_uuid:
    post:
      tags:
      - "(rpc) gen_random_uuid"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/reset_password:
    post:
      tags:
      - "(rpc) reset_password"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          $ref: "#/definitions/args"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_armor_headers:
    post:
      tags:
      - "(rpc) pgp_armor_headers"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_sym_encrypt_bytea:
    post:
      tags:
      - "(rpc) pgp_sym_encrypt_bytea"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_pub_encrypt_bytea:
    post:
      tags:
      - "(rpc) pgp_pub_encrypt_bytea"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/armor:
    post:
      tags:
      - "(rpc) armor"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/signup:
    post:
      tags:
      - "(rpc) signup"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          $ref: "#/definitions/args_1"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/update_users:
    post:
      tags:
      - "(rpc) update_users"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/hmac:
    post:
      tags:
      - "(rpc) hmac"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/dearmor:
    post:
      tags:
      - "(rpc) dearmor"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_sym_decrypt:
    post:
      tags:
      - "(rpc) pgp_sym_decrypt"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_key_id:
    post:
      tags:
      - "(rpc) pgp_key_id"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/decrypt_iv:
    post:
      tags:
      - "(rpc) decrypt_iv"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/decrypt:
    post:
      tags:
      - "(rpc) decrypt"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_pub_decrypt:
    post:
      tags:
      - "(rpc) pgp_pub_decrypt"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/digest:
    post:
      tags:
      - "(rpc) digest"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/request_password_reset:
    post:
      tags:
      - "(rpc) request_password_reset"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          $ref: "#/definitions/args_2"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/login:
    post:
      tags:
      - "(rpc) login"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          $ref: "#/definitions/args_3"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/gen_random_bytes:
    post:
      tags:
      - "(rpc) gen_random_bytes"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_sym_decrypt_bytea:
    post:
      tags:
      - "(rpc) pgp_sym_decrypt_bytea"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/pgp_pub_decrypt_bytea:
    post:
      tags:
      - "(rpc) pgp_pub_decrypt_bytea"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
  /rpc/gen_salt:
    post:
      tags:
      - "(rpc) gen_salt"
      produces:
      - "application/json"
      - "application/vnd.pgrst.object+json"
      parameters:
      - in: "body"
        name: "args"
        required: true
        schema:
          type: "object"
        x-exportParamName: "Args"
      - name: "Prefer"
        in: "header"
        description: "Preference"
        required: false
        type: "string"
        enum:
        - "params=single-object"
        x-exportParamName: "Prefer"
      responses:
        200:
          description: "OK"
definitions:
  args:
    type: "object"
    required:
    - "email"
    - "pass"
    - "token"
    properties:
      email:
        type: "string"
        format: "text"
      token:
        type: "string"
        format: "uuid"
      pass:
        type: "string"
        format: "text"
  args_1:
    type: "object"
    required:
    - "email"
    - "pass"
    properties:
      email:
        type: "string"
        format: "text"
      pass:
        type: "string"
        format: "text"
  args_3:
    type: "object"
    required:
    - "email"
    - "pass"
    properties:
      email:
        type: "string"
        format: "text"
      pass:
        type: "string"
        format: "text"
  args_2:
    type: "object"
    required:
    - "email"
    properties:
      email:
        type: "string"
        format: "text"
parameters:
  preferParams:
    name: "Prefer"
    in: "header"
    description: "Preference"
    required: false
    type: "string"
    enum:
    - "params=single-object"
    x-exportParamName: "Prefer"
  preferReturn:
    name: "Prefer"
    in: "header"
    description: "Preference"
    required: false
    type: "string"
    enum:
    - "return=representation"
    - "return=minimal"
    - "return=none"
  preferCount:
    name: "Prefer"
    in: "header"
    description: "Preference"
    required: false
    type: "string"
    enum:
    - "count=none"
  select:
    name: "select"
    in: "query"
    description: "Filtering Columns"
    required: false
    type: "string"
  order:
    name: "order"
    in: "query"
    description: "Ordering"
    required: false
    type: "string"
  range:
    name: "Range"
    in: "header"
    description: "Limiting and Pagination"
    required: false
    type: "string"
  rangeUnit:
    name: "Range-Unit"
    in: "header"
    description: "Limiting and Pagination"
    required: false
    type: "string"
    default: "items"
  offset:
    name: "offset"
    in: "query"
    description: "Limiting and Pagination"
    required: false
    type: "string"
  limit:
    name: "limit"
    in: "query"
    description: "Limiting and Pagination"
    required: false
    type: "string"
externalDocs:
  description: "PostgREST Documentation"
  url: "https://postgrest.org/en/v5.0/api.html"
